version: "3.7"

networks:
  web:
    external: true

services:
#MariaDB Container
  glpi-db:
    image: mariadb:10.7
    container_name: glpi-db
    hostname: glpi-db
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always
    ports:
      - 3306:3306
    networks:
      - web

#GLPI Container
  glpi:
    image: lambda3/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=America/Sao_Paulo
    restart: always
    networks:
      - web
